CSD-143: Added support for completion to be called with tagEvent.
thedatasherpas/SIFT_SDK_iOS pull request #8
Opened 2020-11-27 19:48 UTC by LamarDataSherpas

https://thedatasherpas.atlassian.net/browse/CSD-143
https://thedatasherpas.atlassian.net/browse/CSD-243
CSD-243: Correct RequiredProperties will be sent with install event.

2020-11-27 20:08 UTC, QasimAbbas approved these changes

2020-11-30 18:36 UTC, QasimAbbas requested changes

2020-11-30 18:36 UTC, QasimAbbas commented on SiftSdkTests/PlanTesting.swift
> +    waitForExpectations(timeout: 10.0)
Is this a bit long to wait for the expectation?

2020-11-30 18:44 UTC, LamarDataSherpas commented on SiftSdkTests/PlanTesting.swift
> +    waitForExpectations(timeout: 10.0)
changed wait to 5 seconds

2020-11-30 20:40 UTC, QasimAbbas requested changes

2020-11-30 20:40 UTC, QasimAbbas commented on SiftSdkTests/PlanTesting.swift
> -    waitForExpectations(timeout: 15.0)
Looks like this was changed to 15s

2020-11-30 20:40 UTC, QasimAbbas commented on SiftSdkTests/PlanTesting.swift
> -      sleep(5)
Should expectation be passed with wait?

2020-12-01 16:08 UTC, QasimAbbas approved these changes

2020-12-01 16:19 UTC, merged